services:
    EventSauce\EventSourcing\Serialization\ObjectMapperPayloadSerializer:
        class: EventSauce\EventSourcing\Serialization\ObjectMapperPayloadSerializer

    EventSauce\EventSourcing\Serialization\ConstructingMessageSerializer:
        class: EventSauce\EventSourcing\Serialization\ConstructingMessageSerializer
        arguments:
            $payloadSerializer: '@EventSauce\EventSourcing\Serialization\ObjectMapperPayloadSerializer'

    EventSauce\IdEncoding\StringIdEncoder:
        class: EventSauce\IdEncoding\StringIdEncoder

    EventSauce\MessageRepository\DoctrineMessageRepository\DoctrineMessageRepository:
        class: EventSauce\MessageRepository\DoctrineMessageRepository\DoctrineMessageRepository
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $tableName: 'message'
            $serializer: '@EventSauce\EventSourcing\Serialization\ConstructingMessageSerializer'
            $aggregateRootIdEncoder: '@EventSauce\IdEncoding\StringIdEncoder'

    EventSauce\EventSourcing\MessageRepository:
        alias: EventSauce\MessageRepository\DoctrineMessageRepository\DoctrineMessageRepository

    EventSauce\EventSourcing\SynchronousMessageDispatcher:
        class: EventSauce\EventSourcing\SynchronousMessageDispatcher
        arguments:
            $consumers:
                - '@Books\Framework\EventSauce\EventDispatcher'

    EventSauce\EventSourcing\MessageDispatcher:
        alias: EventSauce\EventSourcing\SynchronousMessageDispatcher
