parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    Books\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Model/'
            - '../src/Kernel.php'
            - '../src/Event/'
            - '../src/Books/Infrastructure/Response/'
            - '../src/Books/Infrastructure/Request/'

    Books\Books\Infrastructure\Request\BookIdResolver:
        class: Books\Books\Infrastructure\Request\BookIdResolver
        tags:
            - controller.argument_value_resolver:
                name: bookId
                priority: 150
