parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    Books\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Model/'
            - '../src/Kernel.php'
            - '../src/Event/'
            - '../src/Api/Response/'
            - '../src/Api/Request/'

    Books\Api\Request\Book\BookIdResolver:
        class: Books\Api\Request\Book\BookIdResolver
        tags:
            - controller.argument_value_resolver:
                name: bookId
                priority: 150

    Books\Repository\AggregateRoot\BookRepository: ~

