parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    Books\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/*/Domain/'
            - '../src/Kernel.php'
            - '../src/Event/'
            - '../src/*/Infrastructure/Response/'
            - '../src/*/Infrastructure/Request/'
