name: Composer Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      api:
        image: books-api
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - .:/var/www/books
        env:
          APP_ENV: test
        ports:
          - 8000:8000
        options: --expose=8000
      
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: main
          POSTGRES_USER: main
          POSTGRES_DB: books,books_test
        ports:
          - 5432:5432
        options: --expose=5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t books-api .
    
    - name: Run Docker container
      run: docker run --name books-api-container -d -p 8000:8000 books-api
    
    - name: Install Composer dependencies
      run: docker exec books-api-container composer install

    - name: Setup test dependencies
      run: docker exec books-api-container composer build:test
    
    - name: Run tests
      run: docker exec books-api-container composer test
    
    - name: Stop and remove Docker container
      run: |
        docker stop books-api-container
        docker rm books-api-container
