name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: main
          POSTGRES_USER: main
          POSTGRES_DB: books,books_test
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pgsql
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --optimize-autoloader

      - name: Setup test dependencies
        run: composer build:test
        env:
          APP_ENV: test
          DATABASE_URL: postgres://main:main@127.0.0.1:5432/books_test

      - name: Run tests
        run: composer test
        env:
          APP_ENV: test
          DATABASE_URL: postgres://main:main@127.0.0.1:5432/books_test
