name: Build and test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: main
          POSTGRES_USER: main
          POSTGRES_DB: books,books_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t books-api-image -f Dockerfile .
    
    - name: Run Docker container
      run: |
        docker run -d \
          --name books-api \
          -v $PWD:/var/www/books \
          -e APP_ENV=test \
          -e DATABASE_HOST=127.0.0.1 \
          -p 8000:8000 \
          books-api-image \
          symfony server:start --no-tls --port=8000 --dir=/var/www/books
    
    - name: Install Composer dependencies
      run: docker exec books-api composer install

    - name: Setup test dependencies
      run: docker exec books-api composer build:test
    
    - name: Run tests
      run: docker exec books-api composer test
    
    - name: Stop and remove Docker container
      run: |
        docker stop books-api
        docker rm books-api
